spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:trantor2}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:anywhere}
    hikari:
      maxLifetime: 180000
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: false
    hibernate:
      ddl-auto: ${AUTO_DDL_TYPE:update}
    database-platform: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: true